export const people = [
  {
    link: "https://faculty.skoltech.ru/people/maximfedorov",
    alt: "maximfedorov",
    img: "https://www.skoltech.ru/app/data/uploads/sites/19/2018/05/maximfedorov_avatar_1527748400-96x96.jpg",
    name: "Maxim Fedorov",
    description: "Professor, Director, Skoltech Center for Computational and Data-Intensive Science and Engineering",
    position: "faculty",
  },
  {
    link: "https://faculty.skoltech.ru/people/jacobbiamonte",
    alt: "jacobbiamonte",
    img: "https://www.skoltech.ru/app/data/uploads/sites/19/2017/10/jacobbiamonte_avatar_1508518014-96x96.jpeg",
    name: "Jacob Biamonte",
    description: "Associate Professor",
    position: "faculty",
  },
  {
    link: "https://faculty.skoltech.ru/people/nikolaybrilliantov",
    alt: "nikolaybrilliantov",
    img: "https://www.skoltech.ru/app/data/uploads/sites/19/2018/05/nikolaybrilliantov_avatar_1526300792-96x96.png",
    name: "Nikolai Brilliantov",
    description: "Professor",
    position: "faculty",
  },
  {
    link: "https://faculty.skoltech.ru/people/evgenyburnaev",
    alt: "evgenyburnaev",
    img: "https://www.skoltech.ru/app/data/uploads/sites/19/2018/01/evgenyburnaev_avatar_1515439014-96x96.jpg",
    name: "Evgeny Burnaev",
    description: "Associate Professor ",
    position: "faculty",
  },
  {
    link: "https://faculty.skoltech.ru/people/andrzejcichocki",
    alt: "andrzejcichocki",
    img: "https://www.skoltech.ru/app/data/uploads/sites/19/2017/04/andrzejcichocki_avatar_1492517869-96x96.jpg",
    name: "Andrzej Cichocki",
    description: "Professor",
    position: "faculty",
  },
  {
    link: "https://faculty.skoltech.ru/people/dmitrydylov",
    alt: "dmitrydylov",
    img: "https://www.skoltech.ru/app/data/uploads/sites/19/2017/12/dmitrydylov_avatar_1512498454-96x96.jpg",
    name: "Dmitry Dylov",
    description: "Assistant Professor ",
    position: "faculty",
  },
  {
    link: "https://faculty.skoltech.ru/people/gonzaloferrer",
    alt: "gonzaloferrer",
    img: "https://www.skoltech.ru/app/data/uploads/sites/19/2018/01/gonzaloferrer_avatar_1516183206-96x96.jpg",
    name: "Gonzalo Ferrer",
    description: "Assistant Professor ",
    position: "faculty",
  },
  {
    link: "https://faculty.skoltech.ru/people/alexeyfrolov",
    alt: "alexeyfrolov",
    img: "https://www.skoltech.ru/app/data/uploads/sites/19/2017/11/alexeyfrolov_avatar_1509815257-96x96.jpg",
    name: "Alexey Frolov",
    description: "Assistant Professor ",
    position: "faculty",
  },
  {
    link: "https://faculty.skoltech.ru/people/dmitrylakontsev",
    alt: "dmitrylakontsev",
    img: "https://www.skoltech.ru/app/data/uploads/sites/19/2017/12/dmitrylakontsev_avatar_1512463504-96x96.jpg",
    name: "Dmitry Lakontsev",
    description: "Associate Professor of the Practice ",
    position: "faculty",
  },
  {
    link: "https://faculty.skoltech.ru/people/stamatioslefkimmiatis",
    alt: "stamatioslefkimmiatis",
    img: "https://www.skoltech.ru/app/data/uploads/sites/19/2016/05/stamatioslefkimmiatis_avatar_1462969160-96x96.png",
    name: "Stamatis Lefkimmiatis",
    description: "Assistant Professor ",
    position: "faculty",
  },
  {
    link: "https://faculty.skoltech.ru/people/victorlempitsky",
    alt: "victorlempitsky",
    img: "https://www.skoltech.ru/app/data/uploads/sites/19/2014/07/victorlempitsky_avatar_1405517890-96x96.jpg",
    name: "Victor Lempitsky",
    description: "Associate Professor",
    position: "faculty",
  },
  {
    link: "https://faculty.skoltech.ru/people/ivanoseledets",
    alt: "ivanoseledets",
    img: "https://www.skoltech.ru/app/data/uploads/sites/19/2014/07/ivanoseledets_avatar_1405423250-96x96.jpg",
    name: "Ivan Oseledets",
    description: "Associate Professor",
    position: "faculty",
  },
  {
    link: "https://faculty.skoltech.ru/people/anhhuyphan",
    alt: "anhhuyphan",
    img: "https://www.skoltech.ru/app/data/uploads/sites/19/2018/05/anhhuyphan_avatar_1526310782-96x96.jpg",
    name: "Anh-Huy Phan",
    description: "Assistant Professor",
    position: "faculty",
  },
  {
    link: "https://faculty.skoltech.ru/people/petrpopov",
    alt: "petrpopov",
    img: "https://www.skoltech.ru/app/data/uploads/sites/19/2018/08/petrpopov_avatar_1534239504-96x96.jpg",
    name: "Petr Popov",
    description: "Assistant Professor",
    position: "faculty",
  },
  {
    link: "https://faculty.skoltech.ru/people/sergeyrykovanov",
    alt: "sergeyrykovanov",
    img: "https://www.skoltech.ru/app/data/uploads/sites/19/2018/04/sergeyrykovanov_avatar_1523346513-96x96.jpg",
    name: "Sergey Rykovanov",
    description: "Associate Professor ",
    position: "faculty",
  },
  {
    link: "https://faculty.skoltech.ru/people/andreysomov",
    alt: "andreysomov",
    img: "https://www.skoltech.ru/app/data/uploads/sites/19/2017/05/andreysomov_avatar_1493732795-96x96.jpg",
    name: "Andrey Somov",
    description: "Assistant Professor",
    position: "faculty",
  },
  {
    link: "https://faculty.skoltech.ru/people/vladimirspokoiny",
    alt: "vladimirspokoiny",
    img: "https://www.skoltech.ru/app/data/uploads/sites/19/2016/07/vladimirspokoiny_avatar_1467806260-96x96.jpg",
    name: "Vladimir Spokoiny",
    description: "Professor",
    position: "faculty",
  },
  {
    link: "https://faculty.skoltech.ru/people/alexeyvishnyakov",
    alt: "alexeyvishnyakov",
    img: "https://www.skoltech.ru/app/data/uploads/sites/19/2018/01/alexeyvishnyakov_avatar_1516187245-96x96.jpg",
    name: "Alexey Vishnyakov",
    description: "Associate Professor ",
    position: "faculty",
  },
  {
    link: "https://faculty.skoltech.ru/people/deniszorin",
    alt: "deniszorin",
    img: "https://www.skoltech.ru/app/data/uploads/sites/19/2014/07/deniszorin_avatar_1405422803-96x96.jpg",
    name: "Denis Zorin",
    description: "Adjunct Professor",
    position: "faculty",
  }
];
